// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/models/dbmodels"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPlayer(db *gorm.DB, opts ...gen.DOOption) player {
	_player := player{}

	_player.playerDo.UseDB(db, opts...)
	_player.playerDo.UseModel(&dbmodels.Player{})

	tableName := _player.playerDo.TableName()
	_player.ALL = field.NewAsterisk(tableName)
	_player.ID = field.NewUint(tableName, "id")
	_player.CreatedAt = field.NewTime(tableName, "created_at")
	_player.UpdatedAt = field.NewTime(tableName, "updated_at")
	_player.DeletedAt = field.NewField(tableName, "deleted_at")
	_player.Code = field.NewString(tableName, "code")
	_player.RoomID = field.NewUint(tableName, "room_id")
	_player.UserID = field.NewUint(tableName, "user_id")
	_player.NickName = field.NewString(tableName, "nick_name")
	_player.Avatar = field.NewString(tableName, "Avatar")
	_player.Type = field.NewUint(tableName, "type")
	_player.Scores = playerHasManyScores{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Scores", "dbmodels.Scores"),
		Operator: struct {
			field.RelationField
			Scores struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Scores.Operator", "dbmodels.Player"),
			Scores: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scores.Operator.Scores", "dbmodels.Scores"),
			},
		},
	}

	_player.fillFieldMap()

	return _player
}

type player struct {
	playerDo playerDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Code      field.String // 玩家代码
	RoomID    field.Uint   // 房间ID
	UserID    field.Uint   // 用户ID
	NickName  field.String // 昵称
	Avatar    field.String // 头像URL
	Type      field.Uint   // 玩家类型
	Scores    playerHasManyScores

	fieldMap map[string]field.Expr
}

func (p player) Table(newTableName string) *player {
	p.playerDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p player) As(alias string) *player {
	p.playerDo.DO = *(p.playerDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *player) updateTableName(table string) *player {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Code = field.NewString(table, "code")
	p.RoomID = field.NewUint(table, "room_id")
	p.UserID = field.NewUint(table, "user_id")
	p.NickName = field.NewString(table, "nick_name")
	p.Avatar = field.NewString(table, "Avatar")
	p.Type = field.NewUint(table, "type")

	p.fillFieldMap()

	return p
}

func (p *player) WithContext(ctx context.Context) IPlayerDo { return p.playerDo.WithContext(ctx) }

func (p player) TableName() string { return p.playerDo.TableName() }

func (p player) Alias() string { return p.playerDo.Alias() }

func (p player) Columns(cols ...field.Expr) gen.Columns { return p.playerDo.Columns(cols...) }

func (p *player) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *player) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["code"] = p.Code
	p.fieldMap["room_id"] = p.RoomID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["nick_name"] = p.NickName
	p.fieldMap["Avatar"] = p.Avatar
	p.fieldMap["type"] = p.Type

}

func (p player) clone(db *gorm.DB) player {
	p.playerDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Scores.db = db.Session(&gorm.Session{Initialized: true})
	p.Scores.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p player) replaceDB(db *gorm.DB) player {
	p.playerDo.ReplaceDB(db)
	p.Scores.db = db.Session(&gorm.Session{})
	return p
}

type playerHasManyScores struct {
	db *gorm.DB

	field.RelationField

	Operator struct {
		field.RelationField
		Scores struct {
			field.RelationField
		}
	}
}

func (a playerHasManyScores) Where(conds ...field.Expr) *playerHasManyScores {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a playerHasManyScores) WithContext(ctx context.Context) *playerHasManyScores {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a playerHasManyScores) Session(session *gorm.Session) *playerHasManyScores {
	a.db = a.db.Session(session)
	return &a
}

func (a playerHasManyScores) Model(m *dbmodels.Player) *playerHasManyScoresTx {
	return &playerHasManyScoresTx{a.db.Model(m).Association(a.Name())}
}

func (a playerHasManyScores) Unscoped() *playerHasManyScores {
	a.db = a.db.Unscoped()
	return &a
}

type playerHasManyScoresTx struct{ tx *gorm.Association }

func (a playerHasManyScoresTx) Find() (result []*dbmodels.Scores, err error) {
	return result, a.tx.Find(&result)
}

func (a playerHasManyScoresTx) Append(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a playerHasManyScoresTx) Replace(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a playerHasManyScoresTx) Delete(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a playerHasManyScoresTx) Clear() error {
	return a.tx.Clear()
}

func (a playerHasManyScoresTx) Count() int64 {
	return a.tx.Count()
}

func (a playerHasManyScoresTx) Unscoped() *playerHasManyScoresTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type playerDo struct{ gen.DO }

type IPlayerDo interface {
	gen.SubQuery
	Debug() IPlayerDo
	WithContext(ctx context.Context) IPlayerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlayerDo
	WriteDB() IPlayerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlayerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlayerDo
	Not(conds ...gen.Condition) IPlayerDo
	Or(conds ...gen.Condition) IPlayerDo
	Select(conds ...field.Expr) IPlayerDo
	Where(conds ...gen.Condition) IPlayerDo
	Order(conds ...field.Expr) IPlayerDo
	Distinct(cols ...field.Expr) IPlayerDo
	Omit(cols ...field.Expr) IPlayerDo
	Join(table schema.Tabler, on ...field.Expr) IPlayerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlayerDo
	Group(cols ...field.Expr) IPlayerDo
	Having(conds ...gen.Condition) IPlayerDo
	Limit(limit int) IPlayerDo
	Offset(offset int) IPlayerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerDo
	Unscoped() IPlayerDo
	Create(values ...*dbmodels.Player) error
	CreateInBatches(values []*dbmodels.Player, batchSize int) error
	Save(values ...*dbmodels.Player) error
	First() (*dbmodels.Player, error)
	Take() (*dbmodels.Player, error)
	Last() (*dbmodels.Player, error)
	Find() ([]*dbmodels.Player, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Player, err error)
	FindInBatches(result *[]*dbmodels.Player, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbmodels.Player) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlayerDo
	Assign(attrs ...field.AssignExpr) IPlayerDo
	Joins(fields ...field.RelationField) IPlayerDo
	Preload(fields ...field.RelationField) IPlayerDo
	FirstOrInit() (*dbmodels.Player, error)
	FirstOrCreate() (*dbmodels.Player, error)
	FindByPage(offset int, limit int) (result []*dbmodels.Player, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlayerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playerDo) Debug() IPlayerDo {
	return p.withDO(p.DO.Debug())
}

func (p playerDo) WithContext(ctx context.Context) IPlayerDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playerDo) ReadDB() IPlayerDo {
	return p.Clauses(dbresolver.Read)
}

func (p playerDo) WriteDB() IPlayerDo {
	return p.Clauses(dbresolver.Write)
}

func (p playerDo) Session(config *gorm.Session) IPlayerDo {
	return p.withDO(p.DO.Session(config))
}

func (p playerDo) Clauses(conds ...clause.Expression) IPlayerDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playerDo) Returning(value interface{}, columns ...string) IPlayerDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playerDo) Not(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playerDo) Or(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playerDo) Select(conds ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playerDo) Where(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playerDo) Order(conds ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playerDo) Distinct(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playerDo) Omit(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playerDo) Join(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playerDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playerDo) Group(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playerDo) Having(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playerDo) Limit(limit int) IPlayerDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playerDo) Offset(offset int) IPlayerDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playerDo) Unscoped() IPlayerDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playerDo) Create(values ...*dbmodels.Player) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playerDo) CreateInBatches(values []*dbmodels.Player, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playerDo) Save(values ...*dbmodels.Player) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playerDo) First() (*dbmodels.Player, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Player), nil
	}
}

func (p playerDo) Take() (*dbmodels.Player, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Player), nil
	}
}

func (p playerDo) Last() (*dbmodels.Player, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Player), nil
	}
}

func (p playerDo) Find() ([]*dbmodels.Player, error) {
	result, err := p.DO.Find()
	return result.([]*dbmodels.Player), err
}

func (p playerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Player, err error) {
	buf := make([]*dbmodels.Player, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playerDo) FindInBatches(result *[]*dbmodels.Player, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playerDo) Attrs(attrs ...field.AssignExpr) IPlayerDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playerDo) Assign(attrs ...field.AssignExpr) IPlayerDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playerDo) Joins(fields ...field.RelationField) IPlayerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playerDo) Preload(fields ...field.RelationField) IPlayerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playerDo) FirstOrInit() (*dbmodels.Player, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Player), nil
	}
}

func (p playerDo) FirstOrCreate() (*dbmodels.Player, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Player), nil
	}
}

func (p playerDo) FindByPage(offset int, limit int) (result []*dbmodels.Player, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playerDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playerDo) Delete(models ...*dbmodels.Player) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playerDo) withDO(do gen.Dao) *playerDo {
	p.DO = *do.(*gen.DO)
	return p
}
