// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/models/dbmodels"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRoom(db *gorm.DB, opts ...gen.DOOption) room {
	_room := room{}

	_room.roomDo.UseDB(db, opts...)
	_room.roomDo.UseModel(&dbmodels.Room{})

	tableName := _room.roomDo.TableName()
	_room.ALL = field.NewAsterisk(tableName)
	_room.ID = field.NewUint(tableName, "id")
	_room.CreatedAt = field.NewTime(tableName, "created_at")
	_room.UpdatedAt = field.NewTime(tableName, "updated_at")
	_room.DeletedAt = field.NewField(tableName, "deleted_at")
	_room.RoomCode = field.NewString(tableName, "room_code")
	_room.UserID = field.NewUint(tableName, "user_id")
	_room.Players = roomHasManyPlayers{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Players", "dbmodels.Player"),
		Scores: struct {
			field.RelationField
			Operator struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Players.Scores", "dbmodels.Scores"),
			Operator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Players.Scores.Operator", "dbmodels.Player"),
			},
		},
	}

	_room.Scores = roomHasManyScores{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Scores", "dbmodels.Scores"),
	}

	_room.fillFieldMap()

	return _room
}

type room struct {
	roomDo roomDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	RoomCode  field.String // 房间代码
	UserID    field.Uint   // 房主ID
	Players   roomHasManyPlayers

	Scores roomHasManyScores

	fieldMap map[string]field.Expr
}

func (r room) Table(newTableName string) *room {
	r.roomDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r room) As(alias string) *room {
	r.roomDo.DO = *(r.roomDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *room) updateTableName(table string) *room {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RoomCode = field.NewString(table, "room_code")
	r.UserID = field.NewUint(table, "user_id")

	r.fillFieldMap()

	return r
}

func (r *room) WithContext(ctx context.Context) IRoomDo { return r.roomDo.WithContext(ctx) }

func (r room) TableName() string { return r.roomDo.TableName() }

func (r room) Alias() string { return r.roomDo.Alias() }

func (r room) Columns(cols ...field.Expr) gen.Columns { return r.roomDo.Columns(cols...) }

func (r *room) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *room) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["room_code"] = r.RoomCode
	r.fieldMap["user_id"] = r.UserID

}

func (r room) clone(db *gorm.DB) room {
	r.roomDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Players.db = db.Session(&gorm.Session{Initialized: true})
	r.Players.db.Statement.ConnPool = db.Statement.ConnPool
	r.Scores.db = db.Session(&gorm.Session{Initialized: true})
	r.Scores.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r room) replaceDB(db *gorm.DB) room {
	r.roomDo.ReplaceDB(db)
	r.Players.db = db.Session(&gorm.Session{})
	r.Scores.db = db.Session(&gorm.Session{})
	return r
}

type roomHasManyPlayers struct {
	db *gorm.DB

	field.RelationField

	Scores struct {
		field.RelationField
		Operator struct {
			field.RelationField
		}
	}
}

func (a roomHasManyPlayers) Where(conds ...field.Expr) *roomHasManyPlayers {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a roomHasManyPlayers) WithContext(ctx context.Context) *roomHasManyPlayers {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a roomHasManyPlayers) Session(session *gorm.Session) *roomHasManyPlayers {
	a.db = a.db.Session(session)
	return &a
}

func (a roomHasManyPlayers) Model(m *dbmodels.Room) *roomHasManyPlayersTx {
	return &roomHasManyPlayersTx{a.db.Model(m).Association(a.Name())}
}

func (a roomHasManyPlayers) Unscoped() *roomHasManyPlayers {
	a.db = a.db.Unscoped()
	return &a
}

type roomHasManyPlayersTx struct{ tx *gorm.Association }

func (a roomHasManyPlayersTx) Find() (result []*dbmodels.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a roomHasManyPlayersTx) Append(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a roomHasManyPlayersTx) Replace(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a roomHasManyPlayersTx) Delete(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a roomHasManyPlayersTx) Clear() error {
	return a.tx.Clear()
}

func (a roomHasManyPlayersTx) Count() int64 {
	return a.tx.Count()
}

func (a roomHasManyPlayersTx) Unscoped() *roomHasManyPlayersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type roomHasManyScores struct {
	db *gorm.DB

	field.RelationField
}

func (a roomHasManyScores) Where(conds ...field.Expr) *roomHasManyScores {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a roomHasManyScores) WithContext(ctx context.Context) *roomHasManyScores {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a roomHasManyScores) Session(session *gorm.Session) *roomHasManyScores {
	a.db = a.db.Session(session)
	return &a
}

func (a roomHasManyScores) Model(m *dbmodels.Room) *roomHasManyScoresTx {
	return &roomHasManyScoresTx{a.db.Model(m).Association(a.Name())}
}

func (a roomHasManyScores) Unscoped() *roomHasManyScores {
	a.db = a.db.Unscoped()
	return &a
}

type roomHasManyScoresTx struct{ tx *gorm.Association }

func (a roomHasManyScoresTx) Find() (result []*dbmodels.Scores, err error) {
	return result, a.tx.Find(&result)
}

func (a roomHasManyScoresTx) Append(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a roomHasManyScoresTx) Replace(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a roomHasManyScoresTx) Delete(values ...*dbmodels.Scores) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a roomHasManyScoresTx) Clear() error {
	return a.tx.Clear()
}

func (a roomHasManyScoresTx) Count() int64 {
	return a.tx.Count()
}

func (a roomHasManyScoresTx) Unscoped() *roomHasManyScoresTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type roomDo struct{ gen.DO }

type IRoomDo interface {
	gen.SubQuery
	Debug() IRoomDo
	WithContext(ctx context.Context) IRoomDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoomDo
	WriteDB() IRoomDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoomDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoomDo
	Not(conds ...gen.Condition) IRoomDo
	Or(conds ...gen.Condition) IRoomDo
	Select(conds ...field.Expr) IRoomDo
	Where(conds ...gen.Condition) IRoomDo
	Order(conds ...field.Expr) IRoomDo
	Distinct(cols ...field.Expr) IRoomDo
	Omit(cols ...field.Expr) IRoomDo
	Join(table schema.Tabler, on ...field.Expr) IRoomDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoomDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoomDo
	Group(cols ...field.Expr) IRoomDo
	Having(conds ...gen.Condition) IRoomDo
	Limit(limit int) IRoomDo
	Offset(offset int) IRoomDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoomDo
	Unscoped() IRoomDo
	Create(values ...*dbmodels.Room) error
	CreateInBatches(values []*dbmodels.Room, batchSize int) error
	Save(values ...*dbmodels.Room) error
	First() (*dbmodels.Room, error)
	Take() (*dbmodels.Room, error)
	Last() (*dbmodels.Room, error)
	Find() ([]*dbmodels.Room, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Room, err error)
	FindInBatches(result *[]*dbmodels.Room, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbmodels.Room) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoomDo
	Assign(attrs ...field.AssignExpr) IRoomDo
	Joins(fields ...field.RelationField) IRoomDo
	Preload(fields ...field.RelationField) IRoomDo
	FirstOrInit() (*dbmodels.Room, error)
	FirstOrCreate() (*dbmodels.Room, error)
	FindByPage(offset int, limit int) (result []*dbmodels.Room, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoomDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roomDo) Debug() IRoomDo {
	return r.withDO(r.DO.Debug())
}

func (r roomDo) WithContext(ctx context.Context) IRoomDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roomDo) ReadDB() IRoomDo {
	return r.Clauses(dbresolver.Read)
}

func (r roomDo) WriteDB() IRoomDo {
	return r.Clauses(dbresolver.Write)
}

func (r roomDo) Session(config *gorm.Session) IRoomDo {
	return r.withDO(r.DO.Session(config))
}

func (r roomDo) Clauses(conds ...clause.Expression) IRoomDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roomDo) Returning(value interface{}, columns ...string) IRoomDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roomDo) Not(conds ...gen.Condition) IRoomDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roomDo) Or(conds ...gen.Condition) IRoomDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roomDo) Select(conds ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roomDo) Where(conds ...gen.Condition) IRoomDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roomDo) Order(conds ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roomDo) Distinct(cols ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roomDo) Omit(cols ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roomDo) Join(table schema.Tabler, on ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roomDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoomDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roomDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoomDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roomDo) Group(cols ...field.Expr) IRoomDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roomDo) Having(conds ...gen.Condition) IRoomDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roomDo) Limit(limit int) IRoomDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roomDo) Offset(offset int) IRoomDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roomDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoomDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roomDo) Unscoped() IRoomDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roomDo) Create(values ...*dbmodels.Room) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roomDo) CreateInBatches(values []*dbmodels.Room, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roomDo) Save(values ...*dbmodels.Room) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roomDo) First() (*dbmodels.Room, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Room), nil
	}
}

func (r roomDo) Take() (*dbmodels.Room, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Room), nil
	}
}

func (r roomDo) Last() (*dbmodels.Room, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Room), nil
	}
}

func (r roomDo) Find() ([]*dbmodels.Room, error) {
	result, err := r.DO.Find()
	return result.([]*dbmodels.Room), err
}

func (r roomDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Room, err error) {
	buf := make([]*dbmodels.Room, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roomDo) FindInBatches(result *[]*dbmodels.Room, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roomDo) Attrs(attrs ...field.AssignExpr) IRoomDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roomDo) Assign(attrs ...field.AssignExpr) IRoomDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roomDo) Joins(fields ...field.RelationField) IRoomDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roomDo) Preload(fields ...field.RelationField) IRoomDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roomDo) FirstOrInit() (*dbmodels.Room, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Room), nil
	}
}

func (r roomDo) FirstOrCreate() (*dbmodels.Room, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Room), nil
	}
}

func (r roomDo) FindByPage(offset int, limit int) (result []*dbmodels.Room, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roomDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roomDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roomDo) Delete(models ...*dbmodels.Room) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roomDo) withDO(do gen.Dao) *roomDo {
	r.DO = *do.(*gen.DO)
	return r
}
