// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/infra/db/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newBlockedIdentity(db *gorm.DB, opts ...gen.DOOption) blockedIdentity {
	_blockedIdentity := blockedIdentity{}

	_blockedIdentity.blockedIdentityDo.UseDB(db, opts...)
	_blockedIdentity.blockedIdentityDo.UseModel(&models.BlockedIdentity{})

	tableName := _blockedIdentity.blockedIdentityDo.TableName()
	_blockedIdentity.ALL = field.NewAsterisk(tableName)
	_blockedIdentity.ID = field.NewUint(tableName, "id")
	_blockedIdentity.Kind = field.NewString(tableName, "kind")
	_blockedIdentity.Value = field.NewString(tableName, "value")
	_blockedIdentity.CreatedAt = field.NewTime(tableName, "created_at")

	_blockedIdentity.fillFieldMap()

	return _blockedIdentity
}

type blockedIdentity struct {
	blockedIdentityDo blockedIdentityDo

	ALL       field.Asterisk
	ID        field.Uint
	Kind      field.String
	Value     field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (b blockedIdentity) Table(newTableName string) *blockedIdentity {
	b.blockedIdentityDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blockedIdentity) As(alias string) *blockedIdentity {
	b.blockedIdentityDo.DO = *(b.blockedIdentityDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blockedIdentity) updateTableName(table string) *blockedIdentity {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint(table, "id")
	b.Kind = field.NewString(table, "kind")
	b.Value = field.NewString(table, "value")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *blockedIdentity) WithContext(ctx context.Context) IBlockedIdentityDo {
	return b.blockedIdentityDo.WithContext(ctx)
}

func (b blockedIdentity) TableName() string { return b.blockedIdentityDo.TableName() }

func (b blockedIdentity) Alias() string { return b.blockedIdentityDo.Alias() }

func (b blockedIdentity) Columns(cols ...field.Expr) gen.Columns {
	return b.blockedIdentityDo.Columns(cols...)
}

func (b *blockedIdentity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blockedIdentity) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 4)
	b.fieldMap["id"] = b.ID
	b.fieldMap["kind"] = b.Kind
	b.fieldMap["value"] = b.Value
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b blockedIdentity) clone(db *gorm.DB) blockedIdentity {
	b.blockedIdentityDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blockedIdentity) replaceDB(db *gorm.DB) blockedIdentity {
	b.blockedIdentityDo.ReplaceDB(db)
	return b
}

type blockedIdentityDo struct{ gen.DO }

type IBlockedIdentityDo interface {
	gen.SubQuery
	Debug() IBlockedIdentityDo
	WithContext(ctx context.Context) IBlockedIdentityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBlockedIdentityDo
	WriteDB() IBlockedIdentityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBlockedIdentityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBlockedIdentityDo
	Not(conds ...gen.Condition) IBlockedIdentityDo
	Or(conds ...gen.Condition) IBlockedIdentityDo
	Select(conds ...field.Expr) IBlockedIdentityDo
	Where(conds ...gen.Condition) IBlockedIdentityDo
	Order(conds ...field.Expr) IBlockedIdentityDo
	Distinct(cols ...field.Expr) IBlockedIdentityDo
	Omit(cols ...field.Expr) IBlockedIdentityDo
	Join(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo
	Group(cols ...field.Expr) IBlockedIdentityDo
	Having(conds ...gen.Condition) IBlockedIdentityDo
	Limit(limit int) IBlockedIdentityDo
	Offset(offset int) IBlockedIdentityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBlockedIdentityDo
	Unscoped() IBlockedIdentityDo
	Create(values ...*models.BlockedIdentity) error
	CreateInBatches(values []*models.BlockedIdentity, batchSize int) error
	Save(values ...*models.BlockedIdentity) error
	First() (*models.BlockedIdentity, error)
	Take() (*models.BlockedIdentity, error)
	Last() (*models.BlockedIdentity, error)
	Find() ([]*models.BlockedIdentity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.BlockedIdentity, err error)
	FindInBatches(result *[]*models.BlockedIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.BlockedIdentity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBlockedIdentityDo
	Assign(attrs ...field.AssignExpr) IBlockedIdentityDo
	Joins(fields ...field.RelationField) IBlockedIdentityDo
	Preload(fields ...field.RelationField) IBlockedIdentityDo
	FirstOrInit() (*models.BlockedIdentity, error)
	FirstOrCreate() (*models.BlockedIdentity, error)
	FindByPage(offset int, limit int) (result []*models.BlockedIdentity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBlockedIdentityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b blockedIdentityDo) Debug() IBlockedIdentityDo {
	return b.withDO(b.DO.Debug())
}

func (b blockedIdentityDo) WithContext(ctx context.Context) IBlockedIdentityDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blockedIdentityDo) ReadDB() IBlockedIdentityDo {
	return b.Clauses(dbresolver.Read)
}

func (b blockedIdentityDo) WriteDB() IBlockedIdentityDo {
	return b.Clauses(dbresolver.Write)
}

func (b blockedIdentityDo) Session(config *gorm.Session) IBlockedIdentityDo {
	return b.withDO(b.DO.Session(config))
}

func (b blockedIdentityDo) Clauses(conds ...clause.Expression) IBlockedIdentityDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blockedIdentityDo) Returning(value interface{}, columns ...string) IBlockedIdentityDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blockedIdentityDo) Not(conds ...gen.Condition) IBlockedIdentityDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blockedIdentityDo) Or(conds ...gen.Condition) IBlockedIdentityDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blockedIdentityDo) Select(conds ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blockedIdentityDo) Where(conds ...gen.Condition) IBlockedIdentityDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blockedIdentityDo) Order(conds ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blockedIdentityDo) Distinct(cols ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blockedIdentityDo) Omit(cols ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blockedIdentityDo) Join(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blockedIdentityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blockedIdentityDo) RightJoin(table schema.Tabler, on ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blockedIdentityDo) Group(cols ...field.Expr) IBlockedIdentityDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blockedIdentityDo) Having(conds ...gen.Condition) IBlockedIdentityDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blockedIdentityDo) Limit(limit int) IBlockedIdentityDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blockedIdentityDo) Offset(offset int) IBlockedIdentityDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blockedIdentityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBlockedIdentityDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blockedIdentityDo) Unscoped() IBlockedIdentityDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blockedIdentityDo) Create(values ...*models.BlockedIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blockedIdentityDo) CreateInBatches(values []*models.BlockedIdentity, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blockedIdentityDo) Save(values ...*models.BlockedIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blockedIdentityDo) First() (*models.BlockedIdentity, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.BlockedIdentity), nil
	}
}

func (b blockedIdentityDo) Take() (*models.BlockedIdentity, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.BlockedIdentity), nil
	}
}

func (b blockedIdentityDo) Last() (*models.BlockedIdentity, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.BlockedIdentity), nil
	}
}

func (b blockedIdentityDo) Find() ([]*models.BlockedIdentity, error) {
	result, err := b.DO.Find()
	return result.([]*models.BlockedIdentity), err
}

func (b blockedIdentityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.BlockedIdentity, err error) {
	buf := make([]*models.BlockedIdentity, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blockedIdentityDo) FindInBatches(result *[]*models.BlockedIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blockedIdentityDo) Attrs(attrs ...field.AssignExpr) IBlockedIdentityDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blockedIdentityDo) Assign(attrs ...field.AssignExpr) IBlockedIdentityDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blockedIdentityDo) Joins(fields ...field.RelationField) IBlockedIdentityDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blockedIdentityDo) Preload(fields ...field.RelationField) IBlockedIdentityDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blockedIdentityDo) FirstOrInit() (*models.BlockedIdentity, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.BlockedIdentity), nil
	}
}

func (b blockedIdentityDo) FirstOrCreate() (*models.BlockedIdentity, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.BlockedIdentity), nil
	}
}

func (b blockedIdentityDo) FindByPage(offset int, limit int) (result []*models.BlockedIdentity, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blockedIdentityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blockedIdentityDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blockedIdentityDo) Delete(models ...*models.BlockedIdentity) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blockedIdentityDo) withDO(do gen.Dao) *blockedIdentityDo {
	b.DO = *do.(*gen.DO)
	return b
}
