// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/infra/db/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMatchGame(db *gorm.DB, opts ...gen.DOOption) matchGame {
	_matchGame := matchGame{}

	_matchGame.matchGameDo.UseDB(db, opts...)
	_matchGame.matchGameDo.UseModel(&models.MatchGame{})

	tableName := _matchGame.matchGameDo.TableName()
	_matchGame.ALL = field.NewAsterisk(tableName)
	_matchGame.ID = field.NewUint(tableName, "id")
	_matchGame.CreatedAt = field.NewTime(tableName, "created_at")
	_matchGame.UpdatedAt = field.NewTime(tableName, "updated_at")
	_matchGame.DeletedAt = field.NewField(tableName, "deleted_at")
	_matchGame.MatchID = field.NewUint(tableName, "match_id")
	_matchGame.GameNum = field.NewUint(tableName, "game_num")
	_matchGame.StartAt = field.NewInt64(tableName, "start_at")
	_matchGame.EndAt = field.NewInt64(tableName, "end_at")
	_matchGame.Scores = field.NewField(tableName, "scores")
	_matchGame.LastEventID = field.NewUint(tableName, "last_event_id")
	_matchGame.WinnerID = field.NewUint(tableName, "winner_id")
	_matchGame.Winner = matchGameBelongsToWinner{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Winner", "models.Player"),
	}

	_matchGame.LastEvent = matchGameBelongsToLastEvent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LastEvent", "models.MatchEvent"),
	}

	_matchGame.fillFieldMap()

	return _matchGame
}

type matchGame struct {
	matchGameDo matchGameDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	MatchID     field.Uint  // 比赛ID
	GameNum     field.Uint  // 局数
	StartAt     field.Int64 // 开始时间
	EndAt       field.Int64 // 结束时间
	Scores      field.Field // 玩家分数快照
	LastEventID field.Uint  // 最新事件ID
	WinnerID    field.Uint  // 赢家ID
	Winner      matchGameBelongsToWinner

	LastEvent matchGameBelongsToLastEvent

	fieldMap map[string]field.Expr
}

func (m matchGame) Table(newTableName string) *matchGame {
	m.matchGameDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m matchGame) As(alias string) *matchGame {
	m.matchGameDo.DO = *(m.matchGameDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *matchGame) updateTableName(table string) *matchGame {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MatchID = field.NewUint(table, "match_id")
	m.GameNum = field.NewUint(table, "game_num")
	m.StartAt = field.NewInt64(table, "start_at")
	m.EndAt = field.NewInt64(table, "end_at")
	m.Scores = field.NewField(table, "scores")
	m.LastEventID = field.NewUint(table, "last_event_id")
	m.WinnerID = field.NewUint(table, "winner_id")

	m.fillFieldMap()

	return m
}

func (m *matchGame) WithContext(ctx context.Context) IMatchGameDo {
	return m.matchGameDo.WithContext(ctx)
}

func (m matchGame) TableName() string { return m.matchGameDo.TableName() }

func (m matchGame) Alias() string { return m.matchGameDo.Alias() }

func (m matchGame) Columns(cols ...field.Expr) gen.Columns { return m.matchGameDo.Columns(cols...) }

func (m *matchGame) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *matchGame) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["match_id"] = m.MatchID
	m.fieldMap["game_num"] = m.GameNum
	m.fieldMap["start_at"] = m.StartAt
	m.fieldMap["end_at"] = m.EndAt
	m.fieldMap["scores"] = m.Scores
	m.fieldMap["last_event_id"] = m.LastEventID
	m.fieldMap["winner_id"] = m.WinnerID

}

func (m matchGame) clone(db *gorm.DB) matchGame {
	m.matchGameDo.ReplaceConnPool(db.Statement.ConnPool)
	m.Winner.db = db.Session(&gorm.Session{Initialized: true})
	m.Winner.db.Statement.ConnPool = db.Statement.ConnPool
	m.LastEvent.db = db.Session(&gorm.Session{Initialized: true})
	m.LastEvent.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m matchGame) replaceDB(db *gorm.DB) matchGame {
	m.matchGameDo.ReplaceDB(db)
	m.Winner.db = db.Session(&gorm.Session{})
	m.LastEvent.db = db.Session(&gorm.Session{})
	return m
}

type matchGameBelongsToWinner struct {
	db *gorm.DB

	field.RelationField
}

func (a matchGameBelongsToWinner) Where(conds ...field.Expr) *matchGameBelongsToWinner {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchGameBelongsToWinner) WithContext(ctx context.Context) *matchGameBelongsToWinner {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchGameBelongsToWinner) Session(session *gorm.Session) *matchGameBelongsToWinner {
	a.db = a.db.Session(session)
	return &a
}

func (a matchGameBelongsToWinner) Model(m *models.MatchGame) *matchGameBelongsToWinnerTx {
	return &matchGameBelongsToWinnerTx{a.db.Model(m).Association(a.Name())}
}

func (a matchGameBelongsToWinner) Unscoped() *matchGameBelongsToWinner {
	a.db = a.db.Unscoped()
	return &a
}

type matchGameBelongsToWinnerTx struct{ tx *gorm.Association }

func (a matchGameBelongsToWinnerTx) Find() (result *models.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a matchGameBelongsToWinnerTx) Append(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchGameBelongsToWinnerTx) Replace(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchGameBelongsToWinnerTx) Delete(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchGameBelongsToWinnerTx) Clear() error {
	return a.tx.Clear()
}

func (a matchGameBelongsToWinnerTx) Count() int64 {
	return a.tx.Count()
}

func (a matchGameBelongsToWinnerTx) Unscoped() *matchGameBelongsToWinnerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchGameBelongsToLastEvent struct {
	db *gorm.DB

	field.RelationField
}

func (a matchGameBelongsToLastEvent) Where(conds ...field.Expr) *matchGameBelongsToLastEvent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchGameBelongsToLastEvent) WithContext(ctx context.Context) *matchGameBelongsToLastEvent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchGameBelongsToLastEvent) Session(session *gorm.Session) *matchGameBelongsToLastEvent {
	a.db = a.db.Session(session)
	return &a
}

func (a matchGameBelongsToLastEvent) Model(m *models.MatchGame) *matchGameBelongsToLastEventTx {
	return &matchGameBelongsToLastEventTx{a.db.Model(m).Association(a.Name())}
}

func (a matchGameBelongsToLastEvent) Unscoped() *matchGameBelongsToLastEvent {
	a.db = a.db.Unscoped()
	return &a
}

type matchGameBelongsToLastEventTx struct{ tx *gorm.Association }

func (a matchGameBelongsToLastEventTx) Find() (result *models.MatchEvent, err error) {
	return result, a.tx.Find(&result)
}

func (a matchGameBelongsToLastEventTx) Append(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchGameBelongsToLastEventTx) Replace(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchGameBelongsToLastEventTx) Delete(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchGameBelongsToLastEventTx) Clear() error {
	return a.tx.Clear()
}

func (a matchGameBelongsToLastEventTx) Count() int64 {
	return a.tx.Count()
}

func (a matchGameBelongsToLastEventTx) Unscoped() *matchGameBelongsToLastEventTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchGameDo struct{ gen.DO }

type IMatchGameDo interface {
	gen.SubQuery
	Debug() IMatchGameDo
	WithContext(ctx context.Context) IMatchGameDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMatchGameDo
	WriteDB() IMatchGameDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMatchGameDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMatchGameDo
	Not(conds ...gen.Condition) IMatchGameDo
	Or(conds ...gen.Condition) IMatchGameDo
	Select(conds ...field.Expr) IMatchGameDo
	Where(conds ...gen.Condition) IMatchGameDo
	Order(conds ...field.Expr) IMatchGameDo
	Distinct(cols ...field.Expr) IMatchGameDo
	Omit(cols ...field.Expr) IMatchGameDo
	Join(table schema.Tabler, on ...field.Expr) IMatchGameDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMatchGameDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMatchGameDo
	Group(cols ...field.Expr) IMatchGameDo
	Having(conds ...gen.Condition) IMatchGameDo
	Limit(limit int) IMatchGameDo
	Offset(offset int) IMatchGameDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchGameDo
	Unscoped() IMatchGameDo
	Create(values ...*models.MatchGame) error
	CreateInBatches(values []*models.MatchGame, batchSize int) error
	Save(values ...*models.MatchGame) error
	First() (*models.MatchGame, error)
	Take() (*models.MatchGame, error)
	Last() (*models.MatchGame, error)
	Find() ([]*models.MatchGame, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MatchGame, err error)
	FindInBatches(result *[]*models.MatchGame, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MatchGame) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMatchGameDo
	Assign(attrs ...field.AssignExpr) IMatchGameDo
	Joins(fields ...field.RelationField) IMatchGameDo
	Preload(fields ...field.RelationField) IMatchGameDo
	FirstOrInit() (*models.MatchGame, error)
	FirstOrCreate() (*models.MatchGame, error)
	FindByPage(offset int, limit int) (result []*models.MatchGame, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMatchGameDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m matchGameDo) Debug() IMatchGameDo {
	return m.withDO(m.DO.Debug())
}

func (m matchGameDo) WithContext(ctx context.Context) IMatchGameDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m matchGameDo) ReadDB() IMatchGameDo {
	return m.Clauses(dbresolver.Read)
}

func (m matchGameDo) WriteDB() IMatchGameDo {
	return m.Clauses(dbresolver.Write)
}

func (m matchGameDo) Session(config *gorm.Session) IMatchGameDo {
	return m.withDO(m.DO.Session(config))
}

func (m matchGameDo) Clauses(conds ...clause.Expression) IMatchGameDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m matchGameDo) Returning(value interface{}, columns ...string) IMatchGameDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m matchGameDo) Not(conds ...gen.Condition) IMatchGameDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m matchGameDo) Or(conds ...gen.Condition) IMatchGameDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m matchGameDo) Select(conds ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m matchGameDo) Where(conds ...gen.Condition) IMatchGameDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m matchGameDo) Order(conds ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m matchGameDo) Distinct(cols ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m matchGameDo) Omit(cols ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m matchGameDo) Join(table schema.Tabler, on ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m matchGameDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m matchGameDo) RightJoin(table schema.Tabler, on ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m matchGameDo) Group(cols ...field.Expr) IMatchGameDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m matchGameDo) Having(conds ...gen.Condition) IMatchGameDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m matchGameDo) Limit(limit int) IMatchGameDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m matchGameDo) Offset(offset int) IMatchGameDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m matchGameDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchGameDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m matchGameDo) Unscoped() IMatchGameDo {
	return m.withDO(m.DO.Unscoped())
}

func (m matchGameDo) Create(values ...*models.MatchGame) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m matchGameDo) CreateInBatches(values []*models.MatchGame, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m matchGameDo) Save(values ...*models.MatchGame) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m matchGameDo) First() (*models.MatchGame, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchGame), nil
	}
}

func (m matchGameDo) Take() (*models.MatchGame, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchGame), nil
	}
}

func (m matchGameDo) Last() (*models.MatchGame, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchGame), nil
	}
}

func (m matchGameDo) Find() ([]*models.MatchGame, error) {
	result, err := m.DO.Find()
	return result.([]*models.MatchGame), err
}

func (m matchGameDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MatchGame, err error) {
	buf := make([]*models.MatchGame, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m matchGameDo) FindInBatches(result *[]*models.MatchGame, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m matchGameDo) Attrs(attrs ...field.AssignExpr) IMatchGameDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m matchGameDo) Assign(attrs ...field.AssignExpr) IMatchGameDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m matchGameDo) Joins(fields ...field.RelationField) IMatchGameDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m matchGameDo) Preload(fields ...field.RelationField) IMatchGameDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m matchGameDo) FirstOrInit() (*models.MatchGame, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchGame), nil
	}
}

func (m matchGameDo) FirstOrCreate() (*models.MatchGame, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchGame), nil
	}
}

func (m matchGameDo) FindByPage(offset int, limit int) (result []*models.MatchGame, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m matchGameDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m matchGameDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m matchGameDo) Delete(models ...*models.MatchGame) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *matchGameDo) withDO(do gen.Dao) *matchGameDo {
	m.DO = *do.(*gen.DO)
	return m
}
