// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/infra/db/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMatch(db *gorm.DB, opts ...gen.DOOption) match {
	_match := match{}

	_match.matchDo.UseDB(db, opts...)
	_match.matchDo.UseModel(&models.Match{})

	tableName := _match.matchDo.TableName()
	_match.ALL = field.NewAsterisk(tableName)
	_match.ID = field.NewUint(tableName, "id")
	_match.CreatedAt = field.NewTime(tableName, "created_at")
	_match.UpdatedAt = field.NewTime(tableName, "updated_at")
	_match.DeletedAt = field.NewField(tableName, "deleted_at")
	_match.UserID = field.NewUint(tableName, "user_id")
	_match.Status = field.NewUint8(tableName, "status")
	_match.MatchType = field.NewString(tableName, "match_type")
	_match.Config = field.NewField(tableName, "config")
	_match.Players = matchHasManyPlayers{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Players", "models.Player"),
		Events: struct {
			field.RelationField
			Operator struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Players.Events", "models.MatchEvent"),
			Operator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Players.Events.Operator", "models.Player"),
			},
		},
	}

	_match.Events = matchHasManyEvents{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Events", "models.MatchEvent"),
	}

	_match.MatchGames = matchHasManyMatchGames{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MatchGames", "models.MatchGame"),
		Winner: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("MatchGames.Winner", "models.Player"),
		},
	}

	_match.fillFieldMap()

	return _match
}

type match struct {
	matchDo matchDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserID    field.Uint   // 房主ID
	Status    field.Uint8  // 房间状态
	MatchType field.String // 比赛类型
	Config    field.Field  // 比赛配置
	Players   matchHasManyPlayers

	Events matchHasManyEvents

	MatchGames matchHasManyMatchGames

	fieldMap map[string]field.Expr
}

func (m match) Table(newTableName string) *match {
	m.matchDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m match) As(alias string) *match {
	m.matchDo.DO = *(m.matchDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *match) updateTableName(table string) *match {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.UserID = field.NewUint(table, "user_id")
	m.Status = field.NewUint8(table, "status")
	m.MatchType = field.NewString(table, "match_type")
	m.Config = field.NewField(table, "config")

	m.fillFieldMap()

	return m
}

func (m *match) WithContext(ctx context.Context) IMatchDo { return m.matchDo.WithContext(ctx) }

func (m match) TableName() string { return m.matchDo.TableName() }

func (m match) Alias() string { return m.matchDo.Alias() }

func (m match) Columns(cols ...field.Expr) gen.Columns { return m.matchDo.Columns(cols...) }

func (m *match) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *match) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["status"] = m.Status
	m.fieldMap["match_type"] = m.MatchType
	m.fieldMap["config"] = m.Config

}

func (m match) clone(db *gorm.DB) match {
	m.matchDo.ReplaceConnPool(db.Statement.ConnPool)
	m.Players.db = db.Session(&gorm.Session{Initialized: true})
	m.Players.db.Statement.ConnPool = db.Statement.ConnPool
	m.Events.db = db.Session(&gorm.Session{Initialized: true})
	m.Events.db.Statement.ConnPool = db.Statement.ConnPool
	m.MatchGames.db = db.Session(&gorm.Session{Initialized: true})
	m.MatchGames.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m match) replaceDB(db *gorm.DB) match {
	m.matchDo.ReplaceDB(db)
	m.Players.db = db.Session(&gorm.Session{})
	m.Events.db = db.Session(&gorm.Session{})
	m.MatchGames.db = db.Session(&gorm.Session{})
	return m
}

type matchHasManyPlayers struct {
	db *gorm.DB

	field.RelationField

	Events struct {
		field.RelationField
		Operator struct {
			field.RelationField
		}
	}
}

func (a matchHasManyPlayers) Where(conds ...field.Expr) *matchHasManyPlayers {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchHasManyPlayers) WithContext(ctx context.Context) *matchHasManyPlayers {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchHasManyPlayers) Session(session *gorm.Session) *matchHasManyPlayers {
	a.db = a.db.Session(session)
	return &a
}

func (a matchHasManyPlayers) Model(m *models.Match) *matchHasManyPlayersTx {
	return &matchHasManyPlayersTx{a.db.Model(m).Association(a.Name())}
}

func (a matchHasManyPlayers) Unscoped() *matchHasManyPlayers {
	a.db = a.db.Unscoped()
	return &a
}

type matchHasManyPlayersTx struct{ tx *gorm.Association }

func (a matchHasManyPlayersTx) Find() (result []*models.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a matchHasManyPlayersTx) Append(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchHasManyPlayersTx) Replace(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchHasManyPlayersTx) Delete(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchHasManyPlayersTx) Clear() error {
	return a.tx.Clear()
}

func (a matchHasManyPlayersTx) Count() int64 {
	return a.tx.Count()
}

func (a matchHasManyPlayersTx) Unscoped() *matchHasManyPlayersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchHasManyEvents struct {
	db *gorm.DB

	field.RelationField
}

func (a matchHasManyEvents) Where(conds ...field.Expr) *matchHasManyEvents {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchHasManyEvents) WithContext(ctx context.Context) *matchHasManyEvents {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchHasManyEvents) Session(session *gorm.Session) *matchHasManyEvents {
	a.db = a.db.Session(session)
	return &a
}

func (a matchHasManyEvents) Model(m *models.Match) *matchHasManyEventsTx {
	return &matchHasManyEventsTx{a.db.Model(m).Association(a.Name())}
}

func (a matchHasManyEvents) Unscoped() *matchHasManyEvents {
	a.db = a.db.Unscoped()
	return &a
}

type matchHasManyEventsTx struct{ tx *gorm.Association }

func (a matchHasManyEventsTx) Find() (result []*models.MatchEvent, err error) {
	return result, a.tx.Find(&result)
}

func (a matchHasManyEventsTx) Append(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchHasManyEventsTx) Replace(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchHasManyEventsTx) Delete(values ...*models.MatchEvent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchHasManyEventsTx) Clear() error {
	return a.tx.Clear()
}

func (a matchHasManyEventsTx) Count() int64 {
	return a.tx.Count()
}

func (a matchHasManyEventsTx) Unscoped() *matchHasManyEventsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchHasManyMatchGames struct {
	db *gorm.DB

	field.RelationField

	Winner struct {
		field.RelationField
	}
}

func (a matchHasManyMatchGames) Where(conds ...field.Expr) *matchHasManyMatchGames {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchHasManyMatchGames) WithContext(ctx context.Context) *matchHasManyMatchGames {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchHasManyMatchGames) Session(session *gorm.Session) *matchHasManyMatchGames {
	a.db = a.db.Session(session)
	return &a
}

func (a matchHasManyMatchGames) Model(m *models.Match) *matchHasManyMatchGamesTx {
	return &matchHasManyMatchGamesTx{a.db.Model(m).Association(a.Name())}
}

func (a matchHasManyMatchGames) Unscoped() *matchHasManyMatchGames {
	a.db = a.db.Unscoped()
	return &a
}

type matchHasManyMatchGamesTx struct{ tx *gorm.Association }

func (a matchHasManyMatchGamesTx) Find() (result []*models.MatchGame, err error) {
	return result, a.tx.Find(&result)
}

func (a matchHasManyMatchGamesTx) Append(values ...*models.MatchGame) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchHasManyMatchGamesTx) Replace(values ...*models.MatchGame) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchHasManyMatchGamesTx) Delete(values ...*models.MatchGame) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchHasManyMatchGamesTx) Clear() error {
	return a.tx.Clear()
}

func (a matchHasManyMatchGamesTx) Count() int64 {
	return a.tx.Count()
}

func (a matchHasManyMatchGamesTx) Unscoped() *matchHasManyMatchGamesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchDo struct{ gen.DO }

type IMatchDo interface {
	gen.SubQuery
	Debug() IMatchDo
	WithContext(ctx context.Context) IMatchDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMatchDo
	WriteDB() IMatchDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMatchDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMatchDo
	Not(conds ...gen.Condition) IMatchDo
	Or(conds ...gen.Condition) IMatchDo
	Select(conds ...field.Expr) IMatchDo
	Where(conds ...gen.Condition) IMatchDo
	Order(conds ...field.Expr) IMatchDo
	Distinct(cols ...field.Expr) IMatchDo
	Omit(cols ...field.Expr) IMatchDo
	Join(table schema.Tabler, on ...field.Expr) IMatchDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMatchDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMatchDo
	Group(cols ...field.Expr) IMatchDo
	Having(conds ...gen.Condition) IMatchDo
	Limit(limit int) IMatchDo
	Offset(offset int) IMatchDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchDo
	Unscoped() IMatchDo
	Create(values ...*models.Match) error
	CreateInBatches(values []*models.Match, batchSize int) error
	Save(values ...*models.Match) error
	First() (*models.Match, error)
	Take() (*models.Match, error)
	Last() (*models.Match, error)
	Find() ([]*models.Match, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Match, err error)
	FindInBatches(result *[]*models.Match, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Match) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMatchDo
	Assign(attrs ...field.AssignExpr) IMatchDo
	Joins(fields ...field.RelationField) IMatchDo
	Preload(fields ...field.RelationField) IMatchDo
	FirstOrInit() (*models.Match, error)
	FirstOrCreate() (*models.Match, error)
	FindByPage(offset int, limit int) (result []*models.Match, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMatchDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m matchDo) Debug() IMatchDo {
	return m.withDO(m.DO.Debug())
}

func (m matchDo) WithContext(ctx context.Context) IMatchDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m matchDo) ReadDB() IMatchDo {
	return m.Clauses(dbresolver.Read)
}

func (m matchDo) WriteDB() IMatchDo {
	return m.Clauses(dbresolver.Write)
}

func (m matchDo) Session(config *gorm.Session) IMatchDo {
	return m.withDO(m.DO.Session(config))
}

func (m matchDo) Clauses(conds ...clause.Expression) IMatchDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m matchDo) Returning(value interface{}, columns ...string) IMatchDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m matchDo) Not(conds ...gen.Condition) IMatchDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m matchDo) Or(conds ...gen.Condition) IMatchDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m matchDo) Select(conds ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m matchDo) Where(conds ...gen.Condition) IMatchDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m matchDo) Order(conds ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m matchDo) Distinct(cols ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m matchDo) Omit(cols ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m matchDo) Join(table schema.Tabler, on ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m matchDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMatchDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m matchDo) RightJoin(table schema.Tabler, on ...field.Expr) IMatchDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m matchDo) Group(cols ...field.Expr) IMatchDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m matchDo) Having(conds ...gen.Condition) IMatchDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m matchDo) Limit(limit int) IMatchDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m matchDo) Offset(offset int) IMatchDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m matchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m matchDo) Unscoped() IMatchDo {
	return m.withDO(m.DO.Unscoped())
}

func (m matchDo) Create(values ...*models.Match) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m matchDo) CreateInBatches(values []*models.Match, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m matchDo) Save(values ...*models.Match) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m matchDo) First() (*models.Match, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Match), nil
	}
}

func (m matchDo) Take() (*models.Match, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Match), nil
	}
}

func (m matchDo) Last() (*models.Match, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Match), nil
	}
}

func (m matchDo) Find() ([]*models.Match, error) {
	result, err := m.DO.Find()
	return result.([]*models.Match), err
}

func (m matchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Match, err error) {
	buf := make([]*models.Match, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m matchDo) FindInBatches(result *[]*models.Match, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m matchDo) Attrs(attrs ...field.AssignExpr) IMatchDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m matchDo) Assign(attrs ...field.AssignExpr) IMatchDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m matchDo) Joins(fields ...field.RelationField) IMatchDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m matchDo) Preload(fields ...field.RelationField) IMatchDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m matchDo) FirstOrInit() (*models.Match, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Match), nil
	}
}

func (m matchDo) FirstOrCreate() (*models.Match, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Match), nil
	}
}

func (m matchDo) FindByPage(offset int, limit int) (result []*models.Match, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m matchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m matchDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m matchDo) Delete(models ...*models.Match) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *matchDo) withDO(do gen.Dao) *matchDo {
	m.DO = *do.(*gen.DO)
	return m
}
