// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/infra/db/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMatchEvent(db *gorm.DB, opts ...gen.DOOption) matchEvent {
	_matchEvent := matchEvent{}

	_matchEvent.matchEventDo.UseDB(db, opts...)
	_matchEvent.matchEventDo.UseModel(&models.MatchEvent{})

	tableName := _matchEvent.matchEventDo.TableName()
	_matchEvent.ALL = field.NewAsterisk(tableName)
	_matchEvent.ID = field.NewUint(tableName, "id")
	_matchEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_matchEvent.UpdatedAt = field.NewTime(tableName, "updated_at")
	_matchEvent.DeletedAt = field.NewField(tableName, "deleted_at")
	_matchEvent.MatchID = field.NewUint(tableName, "match_id")
	_matchEvent.PlayerID = field.NewUint(tableName, "player_id")
	_matchEvent.OperatorID = field.NewUint(tableName, "operator_id")
	_matchEvent.EventType = field.NewString(tableName, "event_type")
	_matchEvent.Data = field.NewField(tableName, "data")
	_matchEvent.Operator = matchEventBelongsToOperator{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Operator", "models.Player"),
		Events: struct {
			field.RelationField
			Operator struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Operator.Events", "models.MatchEvent"),
			Operator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Operator.Events.Operator", "models.Player"),
			},
		},
	}

	_matchEvent.fillFieldMap()

	return _matchEvent
}

type matchEvent struct {
	matchEventDo matchEventDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	MatchID    field.Uint   // 时间所属比赛 ID
	PlayerID   field.Uint   // 事件涉及的玩家 ID
	OperatorID field.Uint   // 事件操作人 ID
	EventType  field.String // 事件类型
	Data       field.Field  // 事件数据
	Operator   matchEventBelongsToOperator

	fieldMap map[string]field.Expr
}

func (m matchEvent) Table(newTableName string) *matchEvent {
	m.matchEventDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m matchEvent) As(alias string) *matchEvent {
	m.matchEventDo.DO = *(m.matchEventDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *matchEvent) updateTableName(table string) *matchEvent {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MatchID = field.NewUint(table, "match_id")
	m.PlayerID = field.NewUint(table, "player_id")
	m.OperatorID = field.NewUint(table, "operator_id")
	m.EventType = field.NewString(table, "event_type")
	m.Data = field.NewField(table, "data")

	m.fillFieldMap()

	return m
}

func (m *matchEvent) WithContext(ctx context.Context) IMatchEventDo {
	return m.matchEventDo.WithContext(ctx)
}

func (m matchEvent) TableName() string { return m.matchEventDo.TableName() }

func (m matchEvent) Alias() string { return m.matchEventDo.Alias() }

func (m matchEvent) Columns(cols ...field.Expr) gen.Columns { return m.matchEventDo.Columns(cols...) }

func (m *matchEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *matchEvent) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["match_id"] = m.MatchID
	m.fieldMap["player_id"] = m.PlayerID
	m.fieldMap["operator_id"] = m.OperatorID
	m.fieldMap["event_type"] = m.EventType
	m.fieldMap["data"] = m.Data

}

func (m matchEvent) clone(db *gorm.DB) matchEvent {
	m.matchEventDo.ReplaceConnPool(db.Statement.ConnPool)
	m.Operator.db = db.Session(&gorm.Session{Initialized: true})
	m.Operator.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m matchEvent) replaceDB(db *gorm.DB) matchEvent {
	m.matchEventDo.ReplaceDB(db)
	m.Operator.db = db.Session(&gorm.Session{})
	return m
}

type matchEventBelongsToOperator struct {
	db *gorm.DB

	field.RelationField

	Events struct {
		field.RelationField
		Operator struct {
			field.RelationField
		}
	}
}

func (a matchEventBelongsToOperator) Where(conds ...field.Expr) *matchEventBelongsToOperator {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a matchEventBelongsToOperator) WithContext(ctx context.Context) *matchEventBelongsToOperator {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a matchEventBelongsToOperator) Session(session *gorm.Session) *matchEventBelongsToOperator {
	a.db = a.db.Session(session)
	return &a
}

func (a matchEventBelongsToOperator) Model(m *models.MatchEvent) *matchEventBelongsToOperatorTx {
	return &matchEventBelongsToOperatorTx{a.db.Model(m).Association(a.Name())}
}

func (a matchEventBelongsToOperator) Unscoped() *matchEventBelongsToOperator {
	a.db = a.db.Unscoped()
	return &a
}

type matchEventBelongsToOperatorTx struct{ tx *gorm.Association }

func (a matchEventBelongsToOperatorTx) Find() (result *models.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a matchEventBelongsToOperatorTx) Append(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a matchEventBelongsToOperatorTx) Replace(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a matchEventBelongsToOperatorTx) Delete(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a matchEventBelongsToOperatorTx) Clear() error {
	return a.tx.Clear()
}

func (a matchEventBelongsToOperatorTx) Count() int64 {
	return a.tx.Count()
}

func (a matchEventBelongsToOperatorTx) Unscoped() *matchEventBelongsToOperatorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type matchEventDo struct{ gen.DO }

type IMatchEventDo interface {
	gen.SubQuery
	Debug() IMatchEventDo
	WithContext(ctx context.Context) IMatchEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMatchEventDo
	WriteDB() IMatchEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMatchEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMatchEventDo
	Not(conds ...gen.Condition) IMatchEventDo
	Or(conds ...gen.Condition) IMatchEventDo
	Select(conds ...field.Expr) IMatchEventDo
	Where(conds ...gen.Condition) IMatchEventDo
	Order(conds ...field.Expr) IMatchEventDo
	Distinct(cols ...field.Expr) IMatchEventDo
	Omit(cols ...field.Expr) IMatchEventDo
	Join(table schema.Tabler, on ...field.Expr) IMatchEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMatchEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMatchEventDo
	Group(cols ...field.Expr) IMatchEventDo
	Having(conds ...gen.Condition) IMatchEventDo
	Limit(limit int) IMatchEventDo
	Offset(offset int) IMatchEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchEventDo
	Unscoped() IMatchEventDo
	Create(values ...*models.MatchEvent) error
	CreateInBatches(values []*models.MatchEvent, batchSize int) error
	Save(values ...*models.MatchEvent) error
	First() (*models.MatchEvent, error)
	Take() (*models.MatchEvent, error)
	Last() (*models.MatchEvent, error)
	Find() ([]*models.MatchEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MatchEvent, err error)
	FindInBatches(result *[]*models.MatchEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MatchEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMatchEventDo
	Assign(attrs ...field.AssignExpr) IMatchEventDo
	Joins(fields ...field.RelationField) IMatchEventDo
	Preload(fields ...field.RelationField) IMatchEventDo
	FirstOrInit() (*models.MatchEvent, error)
	FirstOrCreate() (*models.MatchEvent, error)
	FindByPage(offset int, limit int) (result []*models.MatchEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMatchEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m matchEventDo) Debug() IMatchEventDo {
	return m.withDO(m.DO.Debug())
}

func (m matchEventDo) WithContext(ctx context.Context) IMatchEventDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m matchEventDo) ReadDB() IMatchEventDo {
	return m.Clauses(dbresolver.Read)
}

func (m matchEventDo) WriteDB() IMatchEventDo {
	return m.Clauses(dbresolver.Write)
}

func (m matchEventDo) Session(config *gorm.Session) IMatchEventDo {
	return m.withDO(m.DO.Session(config))
}

func (m matchEventDo) Clauses(conds ...clause.Expression) IMatchEventDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m matchEventDo) Returning(value interface{}, columns ...string) IMatchEventDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m matchEventDo) Not(conds ...gen.Condition) IMatchEventDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m matchEventDo) Or(conds ...gen.Condition) IMatchEventDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m matchEventDo) Select(conds ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m matchEventDo) Where(conds ...gen.Condition) IMatchEventDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m matchEventDo) Order(conds ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m matchEventDo) Distinct(cols ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m matchEventDo) Omit(cols ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m matchEventDo) Join(table schema.Tabler, on ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m matchEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m matchEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m matchEventDo) Group(cols ...field.Expr) IMatchEventDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m matchEventDo) Having(conds ...gen.Condition) IMatchEventDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m matchEventDo) Limit(limit int) IMatchEventDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m matchEventDo) Offset(offset int) IMatchEventDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m matchEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMatchEventDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m matchEventDo) Unscoped() IMatchEventDo {
	return m.withDO(m.DO.Unscoped())
}

func (m matchEventDo) Create(values ...*models.MatchEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m matchEventDo) CreateInBatches(values []*models.MatchEvent, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m matchEventDo) Save(values ...*models.MatchEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m matchEventDo) First() (*models.MatchEvent, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchEvent), nil
	}
}

func (m matchEventDo) Take() (*models.MatchEvent, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchEvent), nil
	}
}

func (m matchEventDo) Last() (*models.MatchEvent, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchEvent), nil
	}
}

func (m matchEventDo) Find() ([]*models.MatchEvent, error) {
	result, err := m.DO.Find()
	return result.([]*models.MatchEvent), err
}

func (m matchEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MatchEvent, err error) {
	buf := make([]*models.MatchEvent, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m matchEventDo) FindInBatches(result *[]*models.MatchEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m matchEventDo) Attrs(attrs ...field.AssignExpr) IMatchEventDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m matchEventDo) Assign(attrs ...field.AssignExpr) IMatchEventDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m matchEventDo) Joins(fields ...field.RelationField) IMatchEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m matchEventDo) Preload(fields ...field.RelationField) IMatchEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m matchEventDo) FirstOrInit() (*models.MatchEvent, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchEvent), nil
	}
}

func (m matchEventDo) FirstOrCreate() (*models.MatchEvent, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MatchEvent), nil
	}
}

func (m matchEventDo) FindByPage(offset int, limit int) (result []*models.MatchEvent, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m matchEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m matchEventDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m matchEventDo) Delete(models ...*models.MatchEvent) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *matchEventDo) withDO(do gen.Dao) *matchEventDo {
	m.DO = *do.(*gen.DO)
	return m
}
