// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/infra/db/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newScore(db *gorm.DB, opts ...gen.DOOption) score {
	_score := score{}

	_score.scoreDo.UseDB(db, opts...)
	_score.scoreDo.UseModel(&models.Score{})

	tableName := _score.scoreDo.TableName()
	_score.ALL = field.NewAsterisk(tableName)
	_score.ID = field.NewUint(tableName, "id")
	_score.CreatedAt = field.NewTime(tableName, "created_at")
	_score.UpdatedAt = field.NewTime(tableName, "updated_at")
	_score.DeletedAt = field.NewField(tableName, "deleted_at")
	_score.PlayerID = field.NewUint(tableName, "player_id")
	_score.MatchID = field.NewUint(tableName, "match_id")
	_score.OperatorID = field.NewUint(tableName, "operator_id")
	_score.Change = field.NewInt(tableName, "change")
	_score.Total = field.NewInt(tableName, "total")
	_score.Operator = scoreBelongsToOperator{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Operator", "models.Player"),
		Scores: struct {
			field.RelationField
			Operator struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Operator.Scores", "models.Score"),
			Operator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Operator.Scores.Operator", "models.Player"),
			},
		},
	}

	_score.fillFieldMap()

	return _score
}

type score struct {
	scoreDo scoreDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	PlayerID   field.Uint // 操作分数的玩家ID
	MatchID    field.Uint // 操作分数的比赛ID
	OperatorID field.Uint // 操作人ID
	Change     field.Int  // 变化值
	Total      field.Int  // 总分
	Operator   scoreBelongsToOperator

	fieldMap map[string]field.Expr
}

func (s score) Table(newTableName string) *score {
	s.scoreDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s score) As(alias string) *score {
	s.scoreDo.DO = *(s.scoreDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *score) updateTableName(table string) *score {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.PlayerID = field.NewUint(table, "player_id")
	s.MatchID = field.NewUint(table, "match_id")
	s.OperatorID = field.NewUint(table, "operator_id")
	s.Change = field.NewInt(table, "change")
	s.Total = field.NewInt(table, "total")

	s.fillFieldMap()

	return s
}

func (s *score) WithContext(ctx context.Context) IScoreDo { return s.scoreDo.WithContext(ctx) }

func (s score) TableName() string { return s.scoreDo.TableName() }

func (s score) Alias() string { return s.scoreDo.Alias() }

func (s score) Columns(cols ...field.Expr) gen.Columns { return s.scoreDo.Columns(cols...) }

func (s *score) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *score) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["player_id"] = s.PlayerID
	s.fieldMap["match_id"] = s.MatchID
	s.fieldMap["operator_id"] = s.OperatorID
	s.fieldMap["change"] = s.Change
	s.fieldMap["total"] = s.Total

}

func (s score) clone(db *gorm.DB) score {
	s.scoreDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Operator.db = db.Session(&gorm.Session{Initialized: true})
	s.Operator.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s score) replaceDB(db *gorm.DB) score {
	s.scoreDo.ReplaceDB(db)
	s.Operator.db = db.Session(&gorm.Session{})
	return s
}

type scoreBelongsToOperator struct {
	db *gorm.DB

	field.RelationField

	Scores struct {
		field.RelationField
		Operator struct {
			field.RelationField
		}
	}
}

func (a scoreBelongsToOperator) Where(conds ...field.Expr) *scoreBelongsToOperator {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scoreBelongsToOperator) WithContext(ctx context.Context) *scoreBelongsToOperator {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scoreBelongsToOperator) Session(session *gorm.Session) *scoreBelongsToOperator {
	a.db = a.db.Session(session)
	return &a
}

func (a scoreBelongsToOperator) Model(m *models.Score) *scoreBelongsToOperatorTx {
	return &scoreBelongsToOperatorTx{a.db.Model(m).Association(a.Name())}
}

func (a scoreBelongsToOperator) Unscoped() *scoreBelongsToOperator {
	a.db = a.db.Unscoped()
	return &a
}

type scoreBelongsToOperatorTx struct{ tx *gorm.Association }

func (a scoreBelongsToOperatorTx) Find() (result *models.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a scoreBelongsToOperatorTx) Append(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scoreBelongsToOperatorTx) Replace(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scoreBelongsToOperatorTx) Delete(values ...*models.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scoreBelongsToOperatorTx) Clear() error {
	return a.tx.Clear()
}

func (a scoreBelongsToOperatorTx) Count() int64 {
	return a.tx.Count()
}

func (a scoreBelongsToOperatorTx) Unscoped() *scoreBelongsToOperatorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scoreDo struct{ gen.DO }

type IScoreDo interface {
	gen.SubQuery
	Debug() IScoreDo
	WithContext(ctx context.Context) IScoreDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IScoreDo
	WriteDB() IScoreDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IScoreDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IScoreDo
	Not(conds ...gen.Condition) IScoreDo
	Or(conds ...gen.Condition) IScoreDo
	Select(conds ...field.Expr) IScoreDo
	Where(conds ...gen.Condition) IScoreDo
	Order(conds ...field.Expr) IScoreDo
	Distinct(cols ...field.Expr) IScoreDo
	Omit(cols ...field.Expr) IScoreDo
	Join(table schema.Tabler, on ...field.Expr) IScoreDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IScoreDo
	RightJoin(table schema.Tabler, on ...field.Expr) IScoreDo
	Group(cols ...field.Expr) IScoreDo
	Having(conds ...gen.Condition) IScoreDo
	Limit(limit int) IScoreDo
	Offset(offset int) IScoreDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IScoreDo
	Unscoped() IScoreDo
	Create(values ...*models.Score) error
	CreateInBatches(values []*models.Score, batchSize int) error
	Save(values ...*models.Score) error
	First() (*models.Score, error)
	Take() (*models.Score, error)
	Last() (*models.Score, error)
	Find() ([]*models.Score, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Score, err error)
	FindInBatches(result *[]*models.Score, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Score) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IScoreDo
	Assign(attrs ...field.AssignExpr) IScoreDo
	Joins(fields ...field.RelationField) IScoreDo
	Preload(fields ...field.RelationField) IScoreDo
	FirstOrInit() (*models.Score, error)
	FirstOrCreate() (*models.Score, error)
	FindByPage(offset int, limit int) (result []*models.Score, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IScoreDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s scoreDo) Debug() IScoreDo {
	return s.withDO(s.DO.Debug())
}

func (s scoreDo) WithContext(ctx context.Context) IScoreDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scoreDo) ReadDB() IScoreDo {
	return s.Clauses(dbresolver.Read)
}

func (s scoreDo) WriteDB() IScoreDo {
	return s.Clauses(dbresolver.Write)
}

func (s scoreDo) Session(config *gorm.Session) IScoreDo {
	return s.withDO(s.DO.Session(config))
}

func (s scoreDo) Clauses(conds ...clause.Expression) IScoreDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scoreDo) Returning(value interface{}, columns ...string) IScoreDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scoreDo) Not(conds ...gen.Condition) IScoreDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scoreDo) Or(conds ...gen.Condition) IScoreDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scoreDo) Select(conds ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scoreDo) Where(conds ...gen.Condition) IScoreDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scoreDo) Order(conds ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scoreDo) Distinct(cols ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scoreDo) Omit(cols ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scoreDo) Join(table schema.Tabler, on ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scoreDo) LeftJoin(table schema.Tabler, on ...field.Expr) IScoreDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scoreDo) RightJoin(table schema.Tabler, on ...field.Expr) IScoreDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scoreDo) Group(cols ...field.Expr) IScoreDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scoreDo) Having(conds ...gen.Condition) IScoreDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scoreDo) Limit(limit int) IScoreDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scoreDo) Offset(offset int) IScoreDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scoreDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IScoreDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scoreDo) Unscoped() IScoreDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scoreDo) Create(values ...*models.Score) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scoreDo) CreateInBatches(values []*models.Score, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scoreDo) Save(values ...*models.Score) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scoreDo) First() (*models.Score, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Score), nil
	}
}

func (s scoreDo) Take() (*models.Score, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Score), nil
	}
}

func (s scoreDo) Last() (*models.Score, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Score), nil
	}
}

func (s scoreDo) Find() ([]*models.Score, error) {
	result, err := s.DO.Find()
	return result.([]*models.Score), err
}

func (s scoreDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Score, err error) {
	buf := make([]*models.Score, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scoreDo) FindInBatches(result *[]*models.Score, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scoreDo) Attrs(attrs ...field.AssignExpr) IScoreDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scoreDo) Assign(attrs ...field.AssignExpr) IScoreDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scoreDo) Joins(fields ...field.RelationField) IScoreDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scoreDo) Preload(fields ...field.RelationField) IScoreDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scoreDo) FirstOrInit() (*models.Score, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Score), nil
	}
}

func (s scoreDo) FirstOrCreate() (*models.Score, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Score), nil
	}
}

func (s scoreDo) FindByPage(offset int, limit int) (result []*models.Score, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scoreDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scoreDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scoreDo) Delete(models ...*models.Score) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scoreDo) withDO(do gen.Dao) *scoreDo {
	s.DO = *do.(*gen.DO)
	return s
}
