// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/superwhys/billiard-helper/internal/models/dbmodels"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newScores(db *gorm.DB, opts ...gen.DOOption) scores {
	_scores := scores{}

	_scores.scoresDo.UseDB(db, opts...)
	_scores.scoresDo.UseModel(&dbmodels.Scores{})

	tableName := _scores.scoresDo.TableName()
	_scores.ALL = field.NewAsterisk(tableName)
	_scores.ID = field.NewUint(tableName, "id")
	_scores.CreatedAt = field.NewTime(tableName, "created_at")
	_scores.UpdatedAt = field.NewTime(tableName, "updated_at")
	_scores.DeletedAt = field.NewField(tableName, "deleted_at")
	_scores.PlayerID = field.NewUint(tableName, "player_id")
	_scores.RoomID = field.NewUint(tableName, "room_id")
	_scores.OperatorID = field.NewUint(tableName, "operator_id")
	_scores.Change = field.NewInt(tableName, "change")
	_scores.Total = field.NewInt(tableName, "total")
	_scores.Operator = scoresBelongsToOperator{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Operator", "dbmodels.Player"),
		Scores: struct {
			field.RelationField
			Operator struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Operator.Scores", "dbmodels.Scores"),
			Operator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Operator.Scores.Operator", "dbmodels.Player"),
			},
		},
	}

	_scores.fillFieldMap()

	return _scores
}

type scores struct {
	scoresDo scoresDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	PlayerID   field.Uint // 操作分数的玩家ID
	RoomID     field.Uint // 操作分数的房间ID
	OperatorID field.Uint // 操作人ID
	Change     field.Int  // 变化值
	Total      field.Int  // 总分
	Operator   scoresBelongsToOperator

	fieldMap map[string]field.Expr
}

func (s scores) Table(newTableName string) *scores {
	s.scoresDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scores) As(alias string) *scores {
	s.scoresDo.DO = *(s.scoresDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scores) updateTableName(table string) *scores {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.PlayerID = field.NewUint(table, "player_id")
	s.RoomID = field.NewUint(table, "room_id")
	s.OperatorID = field.NewUint(table, "operator_id")
	s.Change = field.NewInt(table, "change")
	s.Total = field.NewInt(table, "total")

	s.fillFieldMap()

	return s
}

func (s *scores) WithContext(ctx context.Context) IScoresDo { return s.scoresDo.WithContext(ctx) }

func (s scores) TableName() string { return s.scoresDo.TableName() }

func (s scores) Alias() string { return s.scoresDo.Alias() }

func (s scores) Columns(cols ...field.Expr) gen.Columns { return s.scoresDo.Columns(cols...) }

func (s *scores) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scores) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["player_id"] = s.PlayerID
	s.fieldMap["room_id"] = s.RoomID
	s.fieldMap["operator_id"] = s.OperatorID
	s.fieldMap["change"] = s.Change
	s.fieldMap["total"] = s.Total

}

func (s scores) clone(db *gorm.DB) scores {
	s.scoresDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Operator.db = db.Session(&gorm.Session{Initialized: true})
	s.Operator.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s scores) replaceDB(db *gorm.DB) scores {
	s.scoresDo.ReplaceDB(db)
	s.Operator.db = db.Session(&gorm.Session{})
	return s
}

type scoresBelongsToOperator struct {
	db *gorm.DB

	field.RelationField

	Scores struct {
		field.RelationField
		Operator struct {
			field.RelationField
		}
	}
}

func (a scoresBelongsToOperator) Where(conds ...field.Expr) *scoresBelongsToOperator {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scoresBelongsToOperator) WithContext(ctx context.Context) *scoresBelongsToOperator {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scoresBelongsToOperator) Session(session *gorm.Session) *scoresBelongsToOperator {
	a.db = a.db.Session(session)
	return &a
}

func (a scoresBelongsToOperator) Model(m *dbmodels.Scores) *scoresBelongsToOperatorTx {
	return &scoresBelongsToOperatorTx{a.db.Model(m).Association(a.Name())}
}

func (a scoresBelongsToOperator) Unscoped() *scoresBelongsToOperator {
	a.db = a.db.Unscoped()
	return &a
}

type scoresBelongsToOperatorTx struct{ tx *gorm.Association }

func (a scoresBelongsToOperatorTx) Find() (result *dbmodels.Player, err error) {
	return result, a.tx.Find(&result)
}

func (a scoresBelongsToOperatorTx) Append(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scoresBelongsToOperatorTx) Replace(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scoresBelongsToOperatorTx) Delete(values ...*dbmodels.Player) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scoresBelongsToOperatorTx) Clear() error {
	return a.tx.Clear()
}

func (a scoresBelongsToOperatorTx) Count() int64 {
	return a.tx.Count()
}

func (a scoresBelongsToOperatorTx) Unscoped() *scoresBelongsToOperatorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scoresDo struct{ gen.DO }

type IScoresDo interface {
	gen.SubQuery
	Debug() IScoresDo
	WithContext(ctx context.Context) IScoresDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IScoresDo
	WriteDB() IScoresDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IScoresDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IScoresDo
	Not(conds ...gen.Condition) IScoresDo
	Or(conds ...gen.Condition) IScoresDo
	Select(conds ...field.Expr) IScoresDo
	Where(conds ...gen.Condition) IScoresDo
	Order(conds ...field.Expr) IScoresDo
	Distinct(cols ...field.Expr) IScoresDo
	Omit(cols ...field.Expr) IScoresDo
	Join(table schema.Tabler, on ...field.Expr) IScoresDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IScoresDo
	RightJoin(table schema.Tabler, on ...field.Expr) IScoresDo
	Group(cols ...field.Expr) IScoresDo
	Having(conds ...gen.Condition) IScoresDo
	Limit(limit int) IScoresDo
	Offset(offset int) IScoresDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IScoresDo
	Unscoped() IScoresDo
	Create(values ...*dbmodels.Scores) error
	CreateInBatches(values []*dbmodels.Scores, batchSize int) error
	Save(values ...*dbmodels.Scores) error
	First() (*dbmodels.Scores, error)
	Take() (*dbmodels.Scores, error)
	Last() (*dbmodels.Scores, error)
	Find() ([]*dbmodels.Scores, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Scores, err error)
	FindInBatches(result *[]*dbmodels.Scores, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbmodels.Scores) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IScoresDo
	Assign(attrs ...field.AssignExpr) IScoresDo
	Joins(fields ...field.RelationField) IScoresDo
	Preload(fields ...field.RelationField) IScoresDo
	FirstOrInit() (*dbmodels.Scores, error)
	FirstOrCreate() (*dbmodels.Scores, error)
	FindByPage(offset int, limit int) (result []*dbmodels.Scores, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IScoresDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s scoresDo) Debug() IScoresDo {
	return s.withDO(s.DO.Debug())
}

func (s scoresDo) WithContext(ctx context.Context) IScoresDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scoresDo) ReadDB() IScoresDo {
	return s.Clauses(dbresolver.Read)
}

func (s scoresDo) WriteDB() IScoresDo {
	return s.Clauses(dbresolver.Write)
}

func (s scoresDo) Session(config *gorm.Session) IScoresDo {
	return s.withDO(s.DO.Session(config))
}

func (s scoresDo) Clauses(conds ...clause.Expression) IScoresDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scoresDo) Returning(value interface{}, columns ...string) IScoresDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scoresDo) Not(conds ...gen.Condition) IScoresDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scoresDo) Or(conds ...gen.Condition) IScoresDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scoresDo) Select(conds ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scoresDo) Where(conds ...gen.Condition) IScoresDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scoresDo) Order(conds ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scoresDo) Distinct(cols ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scoresDo) Omit(cols ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scoresDo) Join(table schema.Tabler, on ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scoresDo) LeftJoin(table schema.Tabler, on ...field.Expr) IScoresDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scoresDo) RightJoin(table schema.Tabler, on ...field.Expr) IScoresDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scoresDo) Group(cols ...field.Expr) IScoresDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scoresDo) Having(conds ...gen.Condition) IScoresDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scoresDo) Limit(limit int) IScoresDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scoresDo) Offset(offset int) IScoresDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scoresDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IScoresDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scoresDo) Unscoped() IScoresDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scoresDo) Create(values ...*dbmodels.Scores) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scoresDo) CreateInBatches(values []*dbmodels.Scores, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scoresDo) Save(values ...*dbmodels.Scores) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scoresDo) First() (*dbmodels.Scores, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Scores), nil
	}
}

func (s scoresDo) Take() (*dbmodels.Scores, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Scores), nil
	}
}

func (s scoresDo) Last() (*dbmodels.Scores, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Scores), nil
	}
}

func (s scoresDo) Find() ([]*dbmodels.Scores, error) {
	result, err := s.DO.Find()
	return result.([]*dbmodels.Scores), err
}

func (s scoresDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.Scores, err error) {
	buf := make([]*dbmodels.Scores, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scoresDo) FindInBatches(result *[]*dbmodels.Scores, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scoresDo) Attrs(attrs ...field.AssignExpr) IScoresDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scoresDo) Assign(attrs ...field.AssignExpr) IScoresDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scoresDo) Joins(fields ...field.RelationField) IScoresDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scoresDo) Preload(fields ...field.RelationField) IScoresDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scoresDo) FirstOrInit() (*dbmodels.Scores, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Scores), nil
	}
}

func (s scoresDo) FirstOrCreate() (*dbmodels.Scores, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.Scores), nil
	}
}

func (s scoresDo) FindByPage(offset int, limit int) (result []*dbmodels.Scores, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scoresDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scoresDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scoresDo) Delete(models ...*dbmodels.Scores) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scoresDo) withDO(do gen.Dao) *scoresDo {
	s.DO = *do.(*gen.DO)
	return s
}
