// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_TokenResponse"
                        }
                    }
                }
            }
        },
        "/account/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_User"
                        }
                    }
                }
            }
        },
        "/account/me/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "更新用户信息请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSelfInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/account/refresh": {
            "post": {
                "description": "使用 refresh token 刷新 access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "刷新 access token",
                "parameters": [
                    {
                        "description": "刷新 Token 请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_TokenResponse"
                        }
                    }
                }
            }
        },
        "/account/register": {
            "post": {
                "description": "注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "注册请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/account/send-email-code": {
            "post": {
                "description": "发送邮箱验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "发送邮箱验证码请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SendRegisterCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/match/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建房间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "创建房间",
                "parameters": [
                    {
                        "description": "创建比赛请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Match"
                        }
                    }
                }
            }
        },
        "/match/detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取比赛详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "获取比赛详情",
                "parameters": [
                    {
                        "description": "获取比赛详情请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatchDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Match"
                        }
                    }
                }
            }
        },
        "/match/end": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "结束比赛",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "结束比赛",
                "parameters": [
                    {
                        "description": "结束比赛请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatchActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/match/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "加入房间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "加入房间",
                "parameters": [
                    {
                        "description": "加入房间请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.JoinMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Match"
                        }
                    }
                }
            }
        },
        "/match/kick": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "踢出玩家",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "踢出玩家",
                "parameters": [
                    {
                        "description": "踢出玩家请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.KickPlayerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/match/leave": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "离开房间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "离开房间",
                "parameters": [
                    {
                        "description": "离开房间请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatchActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/match/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取比赛列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "获取比赛列表",
                "parameters": [
                    {
                        "description": "获取比赛列表请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatchListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-array_dto_Match"
                        }
                    }
                }
            }
        },
        "/match/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "开始比赛",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "开始比赛",
                "parameters": [
                    {
                        "description": "开始比赛请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MatchActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/match/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新比赛",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "更新比赛",
                "parameters": [
                    {
                        "description": "更新比赛请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Match"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateMatchRequest": {
            "type": "object",
            "properties": {
                "match_type": {
                    "$ref": "#/definitions/match.MatchType"
                },
                "max_players": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "target_score": {
                    "type": "integer"
                },
                "virtual_players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Player"
                    }
                }
            }
        },
        "dto.JoinMatchRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "player_type": {
                    "$ref": "#/definitions/match.PlayerType"
                }
            }
        },
        "dto.KickPlayerRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "integer"
                },
                "player_code": {
                    "type": "string"
                }
            }
        },
        "dto.LoginReq": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "verify_code": {
                    "type": "string"
                }
            }
        },
        "dto.Match": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/dto.MatchConfig"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "match_round": {
                    "type": "integer"
                },
                "match_type": {
                    "$ref": "#/definitions/match.MatchType"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Player"
                    }
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "dto.MatchActionRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "integer"
                },
                "player_code": {
                    "type": "string"
                }
            }
        },
        "dto.MatchConfig": {
            "type": "object",
            "properties": {
                "max_players": {
                    "type": "integer"
                },
                "target_score": {
                    "type": "integer"
                }
            }
        },
        "dto.MatchDetailRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "integer"
                }
            }
        },
        "dto.MatchListRequest": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "match_type": {
                    "$ref": "#/definitions/match.MatchType"
                }
            }
        },
        "dto.Player": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "join_time": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/match.PlayerType"
                },
                "user_id": {
                    "description": "真实用户的用户 id",
                    "type": "integer"
                }
            }
        },
        "dto.RefreshTokenReq": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterReq": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.SendRegisterCodeReq": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                }
            }
        },
        "dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateMatchRequest": {
            "type": "object",
            "properties": {
                "match_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "target_score": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateSelfInfoReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "ginutils.Ret-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {}
            }
        },
        "ginutils.Ret-array_dto_Match": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Match"
                    }
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Match": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Match"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_TokenResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.TokenResponse"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.User"
                },
                "message": {}
            }
        },
        "match.MatchType": {
            "type": "string",
            "enum": [
                "snooker",
                "8ball",
                "9ball"
            ],
            "x-enum-varnames": [
                "MatchTypeSnooker",
                "MatchType8Ball",
                "MatchType9Ball"
            ]
        },
        "match.PlayerType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "PlayerTypeVirtual",
                "PlayerTypeReal"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Billiard Helper API",
	Description:      "BilliardHelper",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
