// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-response_TokenResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "注册请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/auth/send-email-code": {
            "post": {
                "description": "发送邮箱验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "发送邮箱验证码请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendEmailCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/rooms/:room_id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取房间详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "获取房间详情",
                "parameters": [
                    {
                        "description": "获取房间详情请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-response_Room"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除房间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "删除房间",
                "parameters": [
                    {
                        "description": "删除房间请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeleteRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/rooms/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建房间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "创建房间",
                "parameters": [
                    {
                        "description": "创建房间请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-response_Room"
                        }
                    }
                }
            }
        },
        "/rooms/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取用户房间列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "获取用户房间列表",
                "parameters": [
                    {
                        "description": "获取用户房间列表请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetUserRoomsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-array_response_Room"
                        }
                    }
                }
            }
        },
        "/scores/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取房间分数列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scores"
                ],
                "summary": "获取房间分数列表",
                "parameters": [
                    {
                        "description": "获取房间分数列表请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetRoomScoresRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-array_response_Scores"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ginutils.Ret-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {}
            }
        },
        "ginutils.Ret-array_response_Room": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Room"
                    }
                },
                "message": {}
            }
        },
        "ginutils.Ret-array_response_Scores": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Scores"
                    }
                },
                "message": {}
            }
        },
        "ginutils.Ret-response_Room": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/response.Room"
                },
                "message": {}
            }
        },
        "ginutils.Ret-response_TokenResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/response.TokenResponse"
                },
                "message": {}
            }
        },
        "request.CreateRoomRequest": {
            "type": "object",
            "required": [
                "room_code",
                "user_id"
            ],
            "properties": {
                "room_code": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "request.DeleteRoomRequest": {
            "type": "object",
            "required": [
                "room_id"
            ],
            "properties": {
                "room_id": {
                    "type": "integer"
                }
            }
        },
        "request.GetRoomRequest": {
            "type": "object",
            "required": [
                "room_id"
            ],
            "properties": {
                "room_id": {
                    "type": "integer"
                }
            }
        },
        "request.GetRoomScoresRequest": {
            "type": "object",
            "required": [
                "room_id"
            ],
            "properties": {
                "room_id": {
                    "type": "integer"
                }
            }
        },
        "request.GetUserRoomsRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "request.LoginReq": {
            "type": "object",
            "required": [
                "email",
                "login_type",
                "secret"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "login_type": {
                    "$ref": "#/definitions/types.LoginType"
                },
                "secret": {
                    "description": "if login type is code, secret is the code\nif login type is password, secret is the password",
                    "type": "string"
                }
            }
        },
        "request.RegisterReq": {
            "type": "object",
            "required": [
                "code",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "request.SendEmailCodeReq": {
            "type": "object",
            "required": [
                "email",
                "scene"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "scene": {
                    "$ref": "#/definitions/types.EmailCodeScene"
                }
            }
        },
        "response.Room": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Player"
                    }
                },
                "room_code": {
                    "type": "string"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Scores"
                    }
                },
                "status": {
                    "$ref": "#/definitions/types.RoomStatus"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.Scores": {
            "type": "object",
            "properties": {
                "change": {
                    "type": "integer"
                },
                "operator": {
                    "$ref": "#/definitions/types.Player"
                },
                "operator_id": {
                    "type": "integer"
                },
                "player_id": {
                    "type": "integer"
                },
                "room_id": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "types.EmailCodeScene": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "EmailCodeSceneRegister",
                "EmailCodeSceneLogin"
            ]
        },
        "types.LoginType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "LoginTypePassword",
                "LoginTypeCode"
            ]
        },
        "types.Player": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_you": {
                    "description": "用来标识返回给客户端的数据时，是否是当前客户端用户",
                    "type": "boolean"
                },
                "nick_name": {
                    "type": "string"
                },
                "room_id": {
                    "type": "integer"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Scores"
                    }
                },
                "type": {
                    "$ref": "#/definitions/types.PlayerType"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "types.PlayerType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "PlayerTypeVirtual",
                "PlayerTypeReal"
            ]
        },
        "types.RoomStatus": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "RoomStatusFinished": "已完成",
                "RoomStatusInProgress": "进行中",
                "RoomStatusPending": "未开始"
            },
            "x-enum-varnames": [
                "RoomStatusPending",
                "RoomStatusInProgress",
                "RoomStatusFinished"
            ]
        },
        "types.Scores": {
            "type": "object",
            "properties": {
                "change": {
                    "type": "integer"
                },
                "operator": {
                    "$ref": "#/definitions/types.Player"
                },
                "operator_id": {
                    "type": "integer"
                },
                "player_id": {
                    "type": "integer"
                },
                "room_id": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Billiard Helper API",
	Description:      "BilliardHelper",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
