basePath: /api
definitions:
  dto.CreateMatchRequest:
    properties:
      match_type:
        $ref: '#/definitions/match.MatchType'
      max_players:
        type: integer
      target_score:
        type: integer
      virtual_players:
        items:
          $ref: '#/definitions/dto.Player'
        type: array
    type: object
  dto.JoinMatchRequest:
    properties:
      match_id:
        type: integer
      nick_name:
        type: string
      player_type:
        $ref: '#/definitions/match.PlayerType'
    type: object
  dto.KickPlayerRequest:
    properties:
      match_id:
        type: integer
      player_code:
        type: string
    type: object
  dto.LoginReq:
    properties:
      account:
        type: string
      password:
        type: string
      verify_code:
        type: string
    type: object
  dto.Match:
    properties:
      config:
        $ref: '#/definitions/dto.MatchConfig'
      created_at:
        type: string
      id:
        type: integer
      owner_id:
        type: integer
      players:
        items:
          $ref: '#/definitions/dto.Player'
        type: array
      status:
        type: integer
    type: object
  dto.MatchActionRequest:
    properties:
      match_id:
        type: integer
      player_code:
        type: string
    type: object
  dto.MatchConfig:
    properties:
      max_players:
        type: integer
      target_score:
        type: integer
    type: object
  dto.MatchDetailRequest:
    properties:
      match_id:
        type: integer
    type: object
  dto.MatchListRequest:
    properties:
      match_type:
        $ref: '#/definitions/match.MatchType'
    type: object
  dto.Player:
    properties:
      code:
        type: string
      id:
        type: integer
      join_time:
        type: string
      nick_name:
        type: string
      type:
        $ref: '#/definitions/match.PlayerType'
      user_id:
        description: 真实用户的用户 id
        type: integer
    type: object
  dto.RefreshTokenReq:
    properties:
      refresh_token:
        type: string
    type: object
  dto.RegisterReq:
    properties:
      account:
        type: string
      code:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  dto.SendRegisterCodeReq:
    properties:
      account:
        type: string
    type: object
  dto.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  ginutils.Ret-any:
    properties:
      code:
        type: integer
      data: {}
      message: {}
    type: object
  ginutils.Ret-array_dto_Match:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/dto.Match'
        type: array
      message: {}
    type: object
  ginutils.Ret-dto_Match:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/dto.Match'
      message: {}
    type: object
  ginutils.Ret-dto_TokenResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/dto.TokenResponse'
      message: {}
    type: object
  ginutils.Ret-dto_User:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/dto.User'
      message: {}
    type: object
  match.MatchType:
    enum:
    - snooker
    - 8ball
    - 9ball
    type: string
    x-enum-varnames:
    - MatchTypeSnooker
    - MatchType8Ball
    - MatchType9Ball
  match.PlayerType:
    enum:
    - 1
    - 2
    format: int32
    type: integer
    x-enum-varnames:
    - PlayerTypeVirtual
    - PlayerTypeReal
info:
  contact: {}
  description: BilliardHelper
  title: Billiard Helper API
  version: "1.0"
paths:
  /account/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_TokenResponse'
      summary: 登录
      tags:
      - Account
  /account/me:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_User'
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - Account
  /account/refresh:
    post:
      consumes:
      - application/json
      description: 使用 refresh token 刷新 access token
      parameters:
      - description: 刷新 Token 请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_TokenResponse'
      summary: 刷新 access token
      tags:
      - Account
  /account/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - description: 注册请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      summary: 注册
      tags:
      - Account
  /account/send-email-code:
    post:
      consumes:
      - application/json
      description: 发送邮箱验证码
      parameters:
      - description: 发送邮箱验证码请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SendRegisterCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      summary: 发送邮箱验证码
      tags:
      - Account
  /match/create:
    post:
      consumes:
      - application/json
      description: 创建房间
      parameters:
      - description: 创建比赛请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateMatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_Match'
      security:
      - BearerAuth: []
      summary: 创建房间
      tags:
      - Match
  /match/detail:
    get:
      consumes:
      - application/json
      description: 获取比赛详情
      parameters:
      - description: 获取比赛详情请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MatchDetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_Match'
      security:
      - BearerAuth: []
      summary: 获取比赛详情
      tags:
      - Match
  /match/end:
    post:
      consumes:
      - application/json
      description: 结束比赛
      parameters:
      - description: 结束比赛请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MatchActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      security:
      - BearerAuth: []
      summary: 结束比赛
      tags:
      - Match
  /match/join:
    post:
      consumes:
      - application/json
      description: 加入房间
      parameters:
      - description: 加入房间请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.JoinMatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-dto_Match'
      security:
      - BearerAuth: []
      summary: 加入房间
      tags:
      - Match
  /match/kick:
    post:
      consumes:
      - application/json
      description: 踢出玩家
      parameters:
      - description: 踢出玩家请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.KickPlayerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      security:
      - BearerAuth: []
      summary: 踢出玩家
      tags:
      - Match
  /match/leave:
    post:
      consumes:
      - application/json
      description: 离开房间
      parameters:
      - description: 离开房间请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MatchActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      security:
      - BearerAuth: []
      summary: 离开房间
      tags:
      - Match
  /match/list:
    get:
      consumes:
      - application/json
      description: 获取比赛列表
      parameters:
      - description: 获取比赛列表请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MatchListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-array_dto_Match'
      security:
      - BearerAuth: []
      summary: 获取比赛列表
      tags:
      - Match
  /match/start:
    post:
      consumes:
      - application/json
      description: 开始比赛
      parameters:
      - description: 开始比赛请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MatchActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginutils.Ret-any'
      security:
      - BearerAuth: []
      summary: 开始比赛
      tags:
      - Match
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
